/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/calendars/years/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List plannable years
     * @description Which years can be planned, and which one to show by default.
     */
    get: operations['listSupportedYears'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calendars/years/{year}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a year's holiday calendar
     * @description Holidays and headline stats for one year.
     */
    get: operations['getYearOverview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Holiday: {
      /** Format: date */
      readonly date: string;
      readonly name: string;
      readonly name_fr: string;
      readonly name_ar: string;
      readonly kind: string;
      readonly weekday: string;
      readonly is_confirmed: boolean;
      readonly uncertainty_days: number;
      readonly is_observed: boolean;
    };
    SupportedYears: {
      readonly years: number[];
      readonly default_year: number;
    };
    YearOverview: {
      readonly year: number;
      readonly weekend: string[];
      readonly stats: components['schemas']['YearStats'];
      readonly holidays: components['schemas']['Holiday'][];
    };
    YearStats: {
      readonly total_days: number;
      readonly workdays: number;
      readonly weekend_days: number;
      readonly holidays_observed: number;
      readonly holidays_lost_to_weekend: number;
      readonly has_estimated_holidays: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listSupportedYears: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportedYears'];
        };
      };
    };
  };
  getYearOverview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        year: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['YearOverview'];
        };
      };
    };
  };
}
