/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/calendars/years/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List plannable years
     * @description Which years can be planned, and which one to show by default.
     */
    get: operations['listSupportedYears'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calendars/years/{year}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a year's holiday calendar
     * @description Holidays and headline stats for one year.
     */
    get: operations['getYearOverview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimizer/plan/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan leave around the public holidays
     * @description Turn a number of leave days into a year's worth of holidays.
     */
    post: operations['createPlan'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Break: {
      /** Format: date */
      readonly start: string;
      /** Format: date */
      readonly end: string;
      readonly total_days: number;
      readonly cost: number;
      /** Format: double */
      readonly efficiency: number;
      readonly leave_days: string[];
      readonly holidays: components['schemas']['HolidayRef'][];
      readonly has_estimated_holidays: boolean;
    };
    Holiday: {
      /** Format: date */
      readonly date: string;
      readonly name: string;
      readonly name_fr: string;
      readonly name_ar: string;
      readonly kind: string;
      readonly weekday: string;
      readonly is_confirmed: boolean;
      readonly uncertainty_days: number;
      readonly is_observed: boolean;
    };
    HolidayRef: {
      /** Format: date */
      readonly date: string;
      readonly name: string;
      readonly is_confirmed: boolean;
    };
    Plan: {
      readonly year: number;
      readonly budget: number;
      readonly strategy: string;
      readonly summary: components['schemas']['PlanSummary'];
      readonly breaks: components['schemas']['Break'][];
    };
    PlanRequestRequest: {
      /** @description Paid leave days the company grants. The only thing the user is asked. */
      days: number;
      /**
       * @description Optional. Defaults to the year the user most likely wants to plan.
       *
       *     * `2026` - 2026
       *     * `2027` - 2027
       */
      year?: components['schemas']['YearEnum'];
      /**
       * @description What 'best' means: most total days off, or one longest break.
       *
       *     * `max_days_off` - max_days_off
       *     * `longest_break` - longest_break
       * @default max_days_off
       */
      strategy: components['schemas']['StrategyEnum'];
    };
    PlanSummary: {
      readonly total_days_off: number;
      readonly leave_used: number;
      readonly leave_unused: number;
      /** Format: double */
      readonly efficiency: number;
      readonly break_count: number;
      readonly longest_break: number;
      readonly has_estimated_holidays: boolean;
    };
    /**
     * @description * `max_days_off` - max_days_off
     *     * `longest_break` - longest_break
     * @enum {string}
     */
    StrategyEnum: 'max_days_off' | 'longest_break';
    SupportedYears: {
      readonly years: number[];
      readonly default_year: number;
    };
    /**
     * @description * `2026` - 2026
     *     * `2027` - 2027
     * @enum {integer}
     */
    YearEnum: 2026 | 2027;
    YearOverview: {
      readonly year: number;
      readonly weekend: string[];
      readonly stats: components['schemas']['YearStats'];
      readonly holidays: components['schemas']['Holiday'][];
    };
    YearStats: {
      readonly total_days: number;
      readonly workdays: number;
      readonly weekend_days: number;
      readonly holidays_observed: number;
      readonly holidays_lost_to_weekend: number;
      readonly has_estimated_holidays: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listSupportedYears: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportedYears'];
        };
      };
    };
  };
  getYearOverview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        year: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['YearOverview'];
        };
      };
    };
  };
  createPlan: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PlanRequestRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PlanRequestRequest'];
        'multipart/form-data': components['schemas']['PlanRequestRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Plan'];
        };
      };
    };
  };
}
