# Generated by Django 5.2.17 on 2026-09-18 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbs_up', models.BooleanField(null=True)),
                ('thumbs_down', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'db_table': 'vacancy_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
