# Generated by Django 5.2.17 on 2026-09-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('year', models.PositiveSmallIntegerField(db_index=True, editable=False, help_text='Derived from date on save. Denormalized so lookups stay trivial.')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('name_fr', models.CharField(blank=True, max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('fixed', 'Fixed Gregorian'), ('hijri', 'Hijri (lunar)')], max_length=8)),
                ('is_confirmed', models.BooleanField(default=True, help_text='False while a lunar date is only an astronomical estimate.')),
                ('uncertainty_days', models.PositiveSmallIntegerField(default=0, help_text='How far the real date may fall from this one, in days.')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['year', 'date'], name='calendars_h_year_842a08_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'slug'), name='unique_holiday_per_year')],
            },
        ),
    ]
